### ISSUE TITLE
"'Tensorflow2ModelStep' object has no attribute 'name'"

### ISSUE THREAD

**Issue by krenusz** [guillaume-chevalier/seq2seq-signal-prediction#21]
Hey,
The issue that after i built up the model the TensorFlow2ModelStep_hyperparamaters and TensorFlow2ModelStep_name runs on arror as "'Tensorflow2ModelStep' object has no attribute 'name'". I have followed the requirements, and im using anaconda distribution. Did someone already face this issue? Sorry for bothering and Thank You for your help.
Yours Truly,
Bence

**Comment by littlegirl6688** [comment]
he updated with a new version a couple days ago.

**Comment by krenusz** [comment]
Thank You, i have tested it, its working
