### ISSUE TITLE
Different input and output dimensions (not lengths)

### ISSUE THREAD

**Issue by tomasn4a** [guillaume-chevalier/seq2seq-signal-prediction#4]
Gillaume, thanks a lot for sharing this, I've been having a lot of fun playing with it. I just had a quick question: would it be possible to have input and output sequences of different dimensions? Like for example, using both sin waves in your example 1 to predict only one of them. I know with the sin waves it wouldn't make sense but you get the idea. Any thoughts on this? Thanks again

**Comment by mateosmasa** [comment]
Guillaume, As you describe in exercise 4, how could it be possible to obtain an unique prediction signal with for example, two input signals ? I mean, introducing exogenous variables into the time series to predict it. Thanks for all.

**Comment by guillaume-chevalier** [comment]
Shouldn't this be as easy as not tying together `output_dim` and `input_dim` by giving them different values, and by providing a suited dataset? What happens if you do that?

The `reshaped_outputs` variable remaps the dimensions from `hidden_dim` to `output_dim` with a FC layer.

**Comment by Sangeethbala** [comment]
Is it possible to use variable input sequence length, similar to what has been implemented for Machine Translation?

**Comment by guillaume-chevalier** [comment]
@Sangeethbala Yes, you could use TensorFlow's Dynamic RNN, or some other things in eager mode for example.

**Comment by guillaume-chevalier** [comment]
I think this issue got fixed by merging #17.
